install.packages("ggplot2") 
library('ggplot2')
library(readr)
data1  <- read.csv("C:/Users/M.Abdullah Khilji/Documents/First_Attempt/coffee_ratings.csv", header=TRUE, stringsAsFactors=FALSE)
head(data1)
install.packages("tidyverse")
library(tidyverse)
glimpse(data1)
library(magrittr)
colnames(data1) %<>% str_replace_all("\\s", "_") %<>% tolower()
colnames(data1)
install.packages("dplyr") 
library(dplyr)
library(dplyr)
data_cleaned <- distinct(data1)
data1
is.na(data1)
data1[complete.cases(data1),]

na.omit(data1)
na.exclude(data1)
install.packages("xray")
library(xray)
anomalies(data1, anomaly_threshold=0.5)
install.packages("skimr")
library(skimr)
skim(data1)
library(dplyr)
# Diagnosis of all numerical variables
diagnose_outlier(data1)
problems(x)
